"""Generate docs/dev/reference/ from the code's docstrings (launch plan 3.5).

Run from the repo root:  python tools/gen_reference.py
It rewrites docs/dev/reference/ completely — never hand-edit those files. RELEASING.md runs it on
every release, and tests/test_docs_references.py fails if it's out of date.

What goes in: each module's docstring, then every top-level function and class (and each class's
methods) with the first paragraph of its docstring. Private helpers are included — in this
codebase the underscore names carry most of the reasoning, and a reference that hid them would
hide the useful half. Nothing is imported: the source is parsed, so generating the reference can't
start a server or touch a realm.
"""
from __future__ import annotations

import ast
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PKG = ROOT / "armada"
OUT = ROOT / "docs" / "dev" / "reference"


def _first_para(doc: str | None) -> str:
    if not doc:
        return ""
    return " ".join(doc.strip().split("\n\n", 1)[0].split())


def _sig(fn) -> str:
    try:
        return f"{fn.name}({ast.unparse(fn.args)})"
    except Exception:  # noqa — a signature we can't print is shown by name only
        print(f"gen_reference: could not render the signature of {fn.name}", file=sys.stderr)
        return f"{fn.name}(…)"


def _module_doc(path: Path) -> tuple[str, str]:
    rel = path.relative_to(ROOT).as_posix()
    tree = ast.parse(path.read_text(encoding="utf-8"))
    lines = [f"# `{rel}`", ""]
    doc = ast.get_docstring(tree)
    lines += [doc.strip(), ""] if doc else ["*(no module docstring)*", ""]
    for node in tree.body:
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            lines += [f"### `{_sig(node)}`", "", _first_para(ast.get_docstring(node)) or "—", ""]
        elif isinstance(node, ast.ClassDef):
            lines += [f"### class `{node.name}`", "", _first_para(ast.get_docstring(node)) or "—", ""]
            for m in node.body:
                if isinstance(m, (ast.FunctionDef, ast.AsyncFunctionDef)):
                    lines += [f"- `{node.name}.{_sig(m)}` — {_first_para(ast.get_docstring(m)) or '—'}"]
            lines.append("")
    summary = _first_para(doc).split(". ")[0][:160] if doc else ""
    return "\n".join(lines).rstrip() + "\n", summary


def generate() -> dict:
    """{relative file name: content} for every page, index included."""
    pages, index = {}, ["# Module reference", "",
                        "*Generated by `tools/gen_reference.py` from the docstrings — don't edit by hand.*", "",
                        "| Module | What it is |", "|---|---|"]
    for path in sorted(PKG.rglob("*.py")):
        if "__pycache__" in path.parts:
            continue
        name = path.relative_to(PKG).as_posix()[:-3].replace("/", ".")
        body, summary = _module_doc(path)
        fn = f"{name}.md"
        pages[fn] = body
        index.append(f"| [`{name}`]({fn}) | {summary.replace('|', '/')} |")
    pages["index.md"] = "\n".join(index) + "\n"
    return pages


def main() -> int:
    pages = generate()
    OUT.mkdir(parents=True, exist_ok=True)
    for old in OUT.glob("*.md"):
        if old.name not in pages:
            old.unlink()
    for fn, text in pages.items():
        (OUT / fn).write_text(text, encoding="utf-8", newline="\n")
    print(f"wrote {len(pages)} pages to {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
